### ISSUE TITLE
About shape completion

### ISSUE THREAD

**Issue by happynear** [xinge008/SSN#1]
https://github.com/xinge008/SSN/blob/master/shape_signature/shape_sig_nuscenes.py#L116
As the code implies, the points are enhanced by their central symmetries in all three views?
I can imagine the bev view. But why it is also applied in profile and front view?

Like this?
![image](https://user-images.githubusercontent.com/3897999/78882537-cb1d6c00-7a8a-11ea-8d8a-dd12a41f1641.png)

**Comment by xinge008** [comment]
Thanks for your interest and question.

In fact, the point cloud of each instance (such car or ped) is hard to possess the detailed structure and small component dut to its sparisity and occlusion. For a car, the point cloud often covers its main body (can be seen as a rectangle). Hence, we use the central symmetry to capture its main characteristic and scale. For these detailed components, the shape template of each category maybe work.

**Comment by meanmee** [comment]
The image is broken.
