### ISSUE TITLE
Can it be used on the head of anchor free?

### ISSUE THREAD

**Issue by tianyuluan** [xinge008/SSN#7]
hello,thanks for your greate works,but i want to know can it be used on the head of anchor free,such as centerpoint ?

**Comment by xinge008** [comment]
To be honest, I haven't try it on anchor-free models.

**Comment by xinge008** [comment]
In fact, these shape signature encoding could act as an auxiliary task, which is easy to be incorporated into the anchor free method, such as centerpoint. I can make a try, but may take a long time.

**Comment by tianyuluan** [comment]
Looking forward to hearing your good news!
